In [1]:
import numpy as np
import params
from basis import *

In [2]:
#case1 
value = np.array((10., #beta_s
                  1.,   #gamma_s
                  1,  #kAon
                  1,  #kAoff
                  1,  #kApon
                  1,  #kApoff
                  1,  #alpha
                  1,  #alphap
                  1,  #alpha_s
                  1,  #alpha_sp
                  1,  #nu
                  1., #nup
                  1., #kBon
                  1., #kBoff
                  1.  #gammaP
                  ))

In [3]:
init = np.array((1,  #A
                 0,  #Ap
                 0,  #AS
                 0,  #ApS
                 1,  #B
                 0,  #BP
                 0,  #P
                 10 #S
                 ))

In [4]:
def cme_gui_test_comp(case,T_test,ind_test,N=10000):
    pf = case.solver([T_test])[0]
    p_cme = marginalize(pf,case.states,ind_test)[1]

    gr = case.run_guillespie(T_test*np.ones(N))
    ind_gui,p_gui = np.unique(gr[:,ind_test],return_counts=True)
    p_gui = normalize(p_gui)

    return p_cme,ind_gui,p_gui

In [5]:
case1 = params.case(init,value)


In [9]:
T_test = np.random.rand()*10
ind_test = -1 #np.random.randint(6)
p_cme,p_gui = cme_gui_test_comp(case1,T_test,ind_test,N=100000)

In [10]:
p_cme,p_gui

(array([1.48353493e-04, 1.23555602e-03, 5.23502370e-03, 1.50174609e-02,
        3.27551663e-02, 5.78481036e-02, 8.60430891e-02, 1.10721300e-01,
        1.25688885e-01, 1.27739561e-01, 1.17582697e-01, 9.89460892e-02,
        7.67047993e-02, 5.51324019e-02, 3.69425460e-02, 2.31861570e-02,
        1.36865984e-02, 7.62596492e-03, 4.02361675e-03, 2.01605452e-03,
        9.61761682e-04, 4.37845244e-04, 1.90624156e-04, 7.95198421e-05,
        3.18404760e-05, 1.22572778e-05, 4.54321048e-06, 1.62346537e-06,
        5.59614705e-07]),
 array([1.9000e-04, 1.2200e-03, 5.4400e-03, 1.4330e-02, 3.1670e-02,
        5.8300e-02, 8.5160e-02, 1.1111e-01, 1.2523e-01, 1.2914e-01,
        1.1763e-01, 9.8100e-02, 7.7010e-02, 5.6480e-02, 3.6580e-02,
        2.3150e-02, 1.3840e-02, 7.4400e-03, 4.1800e-03, 2.0300e-03,
        9.3000e-04, 4.8000e-04, 1.9000e-04, 1.3000e-04, 4.0000e-05]))

In [12]:
p_gui-p_cme

ValueError: operands could not be broadcast together with shapes (25,) (29,) 

In [14]:
gp = np.random.poisson(10,size=400)
normalize(np.unique(gp,return_counts=True)[1])

array([0.005 , 0.005 , 0.02  , 0.0375, 0.065 , 0.0775, 0.1   , 0.1425,
       0.145 , 0.115 , 0.0825, 0.07  , 0.0625, 0.03  , 0.0125, 0.015 ,
       0.01  , 0.0025, 0.0025])

In [15]:
p_gui

array([1.9000e-04, 1.2200e-03, 5.4400e-03, 1.4330e-02, 3.1670e-02,
       5.8300e-02, 8.5160e-02, 1.1111e-01, 1.2523e-01, 1.2914e-01,
       1.1763e-01, 9.8100e-02, 7.7010e-02, 5.6480e-02, 3.6580e-02,
       2.3150e-02, 1.3840e-02, 7.4400e-03, 4.1800e-03, 2.0300e-03,
       9.3000e-04, 4.8000e-04, 1.9000e-04, 1.3000e-04, 4.0000e-05])